dist: precise
sudo: required
language: python
python: 2.7
env:
- TOX_ENV=py27-14
- TOX_ENV=py27-16
- TOX_ENV=py27-17
- TOX_ENV=py27-18
- TOX_ENV=py27-19
- TOX_ENV=py27-110
- TOX_ENV=py33-16
- TOX_ENV=py33-17
- TOX_ENV=py34-16
- TOX_ENV=py34-17
- TOX_ENV=py34-18
- TOX_ENV=py35-18
- TOX_ENV=py35-19
- TOX_ENV=py35-110
- TOX_ENV=pypy-14
- TOX_ENV=pypy-16
- TOX_ENV=pypy-17
- TOX_ENV=pypy-18
- TOX_ENV=pypy-19
- TOX_ENV=pypy-110
- TOX_ENV=docs
- TOX_ENV=flake8
install:
- pip install tox
script:
- tox -e $TOX_ENV
after_success:
- pip install codecov
- codecov -e TOX_ENV
deploy:
  provider: pypi
  user: gremu
  password:
    secure: HAgxb7ebUfIQSfcxtjKoXO3FCBiujCo4GU2lYO8IUPeSdurPG6e+uABzwg88d7Zt1Zuay2eleAJzqhvwU2bCOKr68wjkNw3yWRslvLAMK3vj2LPPoWYsgmLJ1YiOvPloCdD2sIVSmpLEiN5HLUteh5j6D2BUbw67a9S2TXx1J8c=
  on:
    tags: true
    repo: gregmuellegger/django-superform
    condition: "$TOX_ENV = py35-18"
